import { Head, Appear, Image, withDeck } from 'mdx-deck'  // https://github.com/jxnblk/mdx-deck
import { CodeSurfer } from "mdx-deck-code-surfer"
import { FullScreenCode, Invert } from "mdx-deck/layouts";
import nightOwl from "prism-react-renderer/themes/nightOwl"
import ReplIt from "../../components/replit";

## Promise Error Handling 

* doSomethingAsync().then(onSuccess,onError)
* the `onError` will catch errors in `doSomethingAsync` 
* not in `onSuccess`

---

## Promise Error Handling

```javascript
getData().then(function onSuccess() {
    // executes if getData resolves
 }, function onError(errors) { 
     // executes if getData rejects, or throws an error
 })
```

---

## How To Handle an Error If Something Breaks in `onSuccess`?

```javascript
getData().then(function onSuccess() {
    // executes if getData resolves
 }).then(null, function onError(error) {
     // if something fails in getData,
     // or onSuccess - then it will be captured here
 })
```
---

<CodeSurfer
  code={require("!raw-loader!./snippets/promise-errors-1.snippet")}
  theme={nightOwl}
  lang="javascript"
  title="Promise Errors"
  showNumbers
  steps={[
    { notes: `Let's Look at How Errors Flow Through` },
    { lines: [2], notes: "Handles Success or Error of getData" },
    {
      tokens: {
        3: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        2: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
      },
      notes: "Handles Error from the `.then` Above"
    },
    {
      tokens: {
        4: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        3: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
      },
      notes: "Handles Error from the successB Above"
    },
    {
      tokens: {
        2: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       
      },
      notes: "If this resolves OR returns"
    },
    {
      tokens: { 
          2: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
          3: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13] },
      notes: "successB gets the value"
    },
    {
      tokens: {
        2: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       
      },
      notes: "If this rejects or throws"
    },
    {
      tokens: { 
          2: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
          3: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]},
      notes: "successAError gets called"
    },
    { notes: "This is generally not a good pattern" }
  ]}
/>

---

# What Do We Do Then?

---
<CodeSurfer
  code={require("!raw-loader!./snippets/promise-errors-2.snippet")}
  theme={nightOwl}
  lang="javascript"
  title="Single Error Handler"
  showNumbers
  steps={[
    { notes: "Let Errors Fall Through" },
    { lines: [5], notes: "Catches Any Errors That Happen Above" },
  ]}
/>

---
<CodeSurfer
  code={require("!raw-loader!./snippets/promise-errors-3.snippet")}
  theme={nightOwl}
  lang="javascript"
  title="Catch and Release"
  showNumbers
  steps={[
    { notes: "Let errors fall through" },
    { range: [5,8], notes: "Catch and Release" },
    { lines: [6], notes: "Can do localized error handling" },
    { lines: [7], notes: "Pass it onto consumers if needed" },
    {}
  ]}
/>

---
### When Would You Want to Handle an Error Earlier?

#### If You Have a Fall-back Value That Can Continue the Chain

---
<CodeSurfer
  code={require("!raw-loader!./snippets/promise-errors-4.snippet")}
  theme={nightOwl}
  lang="javascript"
  title="Graceful Errors"
  showNumbers
  steps={[
    { notes: "If You Can Gracefully Recover" },
    { lines: [3], notes: "Could Return a Cached Value" },
    { range: [5,6], notes: "And Continue the Chain with the Value" },
    {}
  ]}
/>

---
export default FullScreenCode

## Exploring Errors

<ReplIt src="https://repl.it/@e_schultz/Promise-Error-Handling-start?lite=true"/>

---

## Promise Error Handler

* Unless explicitly rejecting or throwing, returns are treated as a successful resolve

---
export default Invert 

# Break / Q&A

## Up Next: Promise Patterns